on:
  push:
    branches:
      - main
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        uses: wei/curl@v1
        with:
          args: |
          --request POST --header "PRIVATE-TOKEN: JchN3sH-AYTFPsGQ6C39" "https://gitlab.com/api/v4/projects/25886567/mirror/pull"