name: 'Push to Prod'

on:
  push:
    branches:
      - main
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Gitlab mirror via curl
      run: |
        curl --request POST \
        --url https://gitlab.com/api/v4/projects/${{ secrets.MIRROR_PROJECT_ID }}/mirror/pull \
        --header 'PRIVATE-TOKEN: ${{ secrets.GITLAB_PRIVATE_TOKEN }}' \
        --fail
